### ISSUE TITLE
SyntaxError: invalid syntax line 88

### ISSUE THREAD

**Issue by Apets** [akme/lsofgraph-python#1]
File "lsofgraph.py", line 88
    ps = {file['d'], n}
                   ^
SyntaxError: invalid syntax
************************************
Python 2.6.9
SUSE Linux Enterprise Server 11SP4 (x86_64)

**Comment by akme** [comment]
Python 2.6 has different dict notation, could you try to change from:
ps = {file['d'], n}
to:
ps = set([file['d'], n])
i don't have python 2.6 to test

**Comment by Apets** [comment]
That helped, thank you.
It was needed to change the line 102 as well, to ps = set([a, b])
