### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by a-khakimov** [akme/lsofgraph-python#3]
```bash
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse file system /run/user/1000/doc
      Output information may be incomplete.
Traceback (most recent call last):
  File "lsofgraph.py", line 183, in <module>
    print_graph(procs, conns)
  File "lsofgraph.py", line 168, in print_graph
    if files[0]['proc'] != files[1]['proc']:
RuntimeError: maximum recursion depth exceeded in cmp
Error: <stdin>: syntax error in line 295 near ''
```

**Comment by akme** [comment]
made some changes, could u please test?

**Comment by a-khakimov** [comment]
I did not make any changes. Just downloaded repo and ran command from readme.
I use ```Python 2.7.12```

**Comment by akme** [comment]
I did some changes, pull them and test if it fails, please

**Comment by a-khakimov** [comment]
unfortunately nothing has changed
same mistake

**Comment by widgetii** [comment]
Seems that I have same mistake also, script just from git

I use Centos 4.9 in Docker environment

```Traceback (most recent call last):
  File "lsofgraph.py", line 183, in <module>
    print_graph(procs, conns)
  File "lsofgraph.py", line 168, in print_graph
    if files[0]['proc'] != files[1]['proc']:
RuntimeError: maximum recursion depth exceeded in cmp
Error: <stdin>: syntax error in line 15

**Comment by akme** [comment]
Could you please try to set higher limit for recursion?
Like this:
sys.setrecursionlimit(15000)

**Comment by widgetii** [comment]
I tried to add, but still same error

Here is my dump of lsof output
[lsof.zip](https://github.com/akme/lsofgraph-python/files/1937132/lsof.zip)

**Comment by powerpxe** [comment]
Does not help adding a line sys.setrecursionlimit(15000). Python 2.7.12 Linux Mint 18.3.
Use ssh -l root 11.10.23.200 'lsof -n -F' | python lsofgraph.py | unflatten -l 1 -c 6 | dot -T jpg > /tmp/a.jpg

Python answer:
File "lsofgraph.py", line 184, in <module>
    print_graph(procs, conns)
  File "lsofgraph.py", line 169, in print_graph
    if files[0]['proc'] != files[1]['proc']:
RuntimeError: maximum recursion depth exceeded in cmp
Error: <stdin>: syntax error in line 72 near ''
------------------------------------------------
ssh is connected to the kernel 2.4.32, lsof version 4.77.
